# Generated by Django 2.1.1 on 2018-09-12 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('foto', models.ImageField(upload_to='photos/')),
                ('pub_fecha', models.DateField(auto_now_add=True)),
                ('favorita', models.BooleanField(default=False)),
                ('comentario', models.CharField(blank=True, max_length=200)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AlbumFotos.Categoria')),
            ],
        ),
    ]
